grep -E '^[A-Za-z0-9_.-]+@[A-Za-z0-9]+\.[A-Za-z]+$' base1.txt > unsorted.txt
grep -E '^[A-Za-z0-9_.-]+@[A-Za-z0-9]+\.[A-Za-z]+$' base2.txt > unsorted.txt
grep -E '^[A-Za-z0-9_.-]+@[A-Za-z0-9]+\.[A-Za-z]+$' base3.txt > unsorted.txt
grep -E '^[A-Za-z0-9_.-]+@[A-Za-z0-9]+\.[A-Za-z]+$' base4.txt > unsorted.txt
grep -E '^[A-Za-z0-9_.-]+@[A-Za-z0-9]+\.[A-Za-z]+$' base5.txt > unsorted.txt
sort unsorted.txt > sorted.txt
